---
title: "Generate QC Report"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Generate QC Report}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r render, echo=FALSE}
library(metaboprep2)

# the data
data_file <- system.file("extdata", "metabolon_v1_example.xlsx", package = "metaboprep2")

# create the object
metabolites <- Metabolites(project_name = "MYPROJECT",
                           format       = "metabolon_v1",
                           filepath     = data_file)

# import the data
metabolites <- import_data(metabolites)

# run QC
metabolites <- metabolite_qc(metabolites, source="raw")

# render report
generate_report(metabolites,
                output_dir=getwd(),
                output_filename=NULL,
                format="html",
                template="qc_report")

print(getwd())

file.copy(file.path(getwd(), "myproject_metaboprep2_qc_report.html"), 
          file.path(getwd(), "../docs/articles/myproject_metaboprep2_qc_report.html"), overwrite = TRUE)
```

```{r, echo=FALSE, results="asis"}
cat('
<div id="iframe-container" style="width: 100%;">
  <iframe id="myIframe" src="https://nicksunderland.github.io/metaboprep2/articles/myproject_metaboprep2_qc_report.html" 
          width="100%" style="border: none;"></iframe>
</div>

<script>
  function resizeIframe() {
    var iframe = document.getElementById("myIframe");
    if (iframe) {
      iframe.style.height = iframe.contentWindow.document.body.scrollHeight + "px";
    }
  }

  document.getElementById("myIframe").onload = function() {
    setTimeout(resizeIframe, 500);
  };
</script>
')
```
